import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    screens: {
      md: "768px",
      lg: "1440px",
      xl: "1920px",
    },
    extend: {
      colors: {
        "text-primary": "var(--color-text-primary)",
        "text-primary-low": "var(--color-text-primary-low)",
        "text-secondary-low": "var(--color-text-secondary-low)",
        "bg-primary": "var(--color-bg-primary)",
        "bg-secondary": "var(--color-bg-secondary)",
        "shape-decorative": "var(--color-shape-decorative)",
        "shape-decorative-low": "var(--color-shape-decorative-low)",
        "border-subtle": "var(--color-border-subtle)",
        "card-vivo": "var(--color-card-vivo)",
        "card-praseg": "var(--color-card-praseg)",
        "card-twism": "var(--color-card-twism)",
      },
      fontFamily: {
        "space-grotesk": ['"Space Grotesk"', "sans-serif"],
        inter: ['"Inter"', "sans-serif"],
        "basis-grotesque": [
          '"Basis Grotesque Arabic Pro"',
          '"Inter"',
          "sans-serif",
        ],
      },
      fontSize: {
        "display-hero-xl": ["328px", { lineHeight: "0.985", letterSpacing: "0" }],
        "display-hero-lg": ["232px", { lineHeight: "0.985", letterSpacing: "0" }],
        "display-hero-md": ["104px", { lineHeight: "0.985", letterSpacing: "0" }],
        "display-hero-sm": ["64px", { lineHeight: "1.05", letterSpacing: "0" }],
        "display-footer-xl": ["272px", { lineHeight: "0.985", letterSpacing: "0" }],
        "display-footer-lg": ["200px", { lineHeight: "0.98", letterSpacing: "0" }],
        "display-footer-md": ["112px", { lineHeight: "0.98", letterSpacing: "0" }],
        "display-footer-sm": ["48px", { lineHeight: "1.05", letterSpacing: "0" }],
        "display-section-xl": ["176px", { lineHeight: "0.985", letterSpacing: "0" }],
        "display-section-lg": ["104px", { lineHeight: "1.1", letterSpacing: "0" }],
        "display-section-md": ["64px", { lineHeight: "1.1", letterSpacing: "0" }],
        "display-section-sm": ["48px", { lineHeight: "1.1", letterSpacing: "0" }],
        "display-role-xl": ["112px", { lineHeight: "0.985", letterSpacing: "0" }],
        "display-role-lg": ["88px", { lineHeight: "0.985", letterSpacing: "0" }],
        "display-role-md": ["64px", { lineHeight: "0.985", letterSpacing: "0" }],
        "display-role-sm": ["48px", { lineHeight: "1.1", letterSpacing: "0" }],
        "display-name-xl": ["104px", { lineHeight: "0.985", letterSpacing: "0" }],
        "display-name-lg": ["72px", { lineHeight: "1.1", letterSpacing: "0" }],
        "display-name-md": ["56px", { lineHeight: "1", letterSpacing: "0" }],
        "display-name-sm": ["48px", { lineHeight: "1.1", letterSpacing: "0" }],
        "heading-card-lg": ["32px", { lineHeight: "0.985", letterSpacing: "2.56px" }],
        "heading-card-sm": ["24px", { lineHeight: "1.2", letterSpacing: "0.96px" }],
        "heading-role": ["32px", { lineHeight: "0.985", letterSpacing: "0.32px" }],
        "body-xl": ["20px", { lineHeight: "1.6", letterSpacing: "0" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "0" }],
        "body-sm": ["16px", { lineHeight: "1.6", letterSpacing: "0" }],
        "card-subtitle-lg": ["24px", { lineHeight: "1.5", letterSpacing: "0" }],
        "card-subtitle-sm": ["16px", { lineHeight: "1.5", letterSpacing: "0" }],
        "label-xl": ["20px", { lineHeight: "0.985", letterSpacing: "1.2px" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.84px" }],
        "contact-label-xl": ["20px", { lineHeight: "1.5", letterSpacing: "0" }],
        "contact-label-lg": ["18px", { lineHeight: "1.5", letterSpacing: "0" }],
        "contact-label-md": ["14px", { lineHeight: "1.5", letterSpacing: "0" }],
        "contact-label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0" }],
        "contact-value-xl": ["24px", { lineHeight: "1.5", letterSpacing: "0" }],
        "contact-value-lg": ["20px", { lineHeight: "1.5", letterSpacing: "0" }],
        "contact-value-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0" }],
        "keyword-xl": ["20px", { lineHeight: "1.5", letterSpacing: "0" }],
        "keyword-md": ["14px", { lineHeight: "1.5", letterSpacing: "0" }],
        "keyword-sm": ["12px", { lineHeight: "1.5", letterSpacing: "0" }],
        "experience-date-xl": ["24px", { lineHeight: "1.5", letterSpacing: "0" }],
        "experience-date-md": ["20px", { lineHeight: "1.5", letterSpacing: "0" }],
        "experience-date-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0" }],
        "about-role-xl": ["40px", { lineHeight: "1.5", letterSpacing: "0" }],
        "about-role-lg": ["24px", { lineHeight: "1.4", letterSpacing: "0" }],
        "about-role-md": ["20px", { lineHeight: "1.4", letterSpacing: "0" }],
        "about-role-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0" }],
        "nav-selected": ["16px", { lineHeight: "normal", letterSpacing: "0.96px" }],
        "nav-default": ["16px", { lineHeight: "normal", letterSpacing: "0.64px" }],
      },
      spacing: {
        "section-px-xl": "96px",
        "section-px-md": "40px",
        "section-px-sm": "24px",
        "section-py-xl": "152px",
        "section-py-lg": "144px",
        "section-py-md": "96px",
        "section-py-sm": "56px",
        "navbar-h": "88px",
        "navbar-gap": "80px",
        "grid-gap-x": "48px",
        "grid-gap-y": "128px",
        "card-stack-md": "88px",
        "card-stack-sm": "32px",
      },
      borderColor: {
        subtle: "var(--color-border-subtle)",
      },
    },
  },
  plugins: [],
} satisfies Config;
